version: '3'
services:
  poster-mongo:
    image: mongo
    container_name: poster-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    env_file:
      - .env  
    ports:
      - 27017:27017
  poster-redis:
    image: redis:7
    command: >
      --requirepass ${REDIS_PASSWORD}
    container_name: poster-redis
    env_file:
      - .env 
    ports:
      - 6379:6379
      

  poster-backend:
    depends_on:
      - poster-mongo
    build: 
      context: .  #当前目录
      dockerfile: Dockerfile #基于Dockerfile构建
    image: poster-backend
    container_name: poster-backend
    ports:
      - 7001:7001
    env_file:
      - .env   
